### ISSUE TITLE
Missing documentation.

### ISSUE THREAD

**Issue by pvdmarel** [miken32/rancid-aruba#5]
I was initially hoping this would work out of the box for the Aruba 2930M devices currently in use at our company, and I did find a few things that should go into some documentation, at least in my opinion. The clogin causes a TimeOut and rancid causes an "End of run not found".
For the Aruba 2930 devices the script used is hrancid and the login to be used is hlogin. The cisco style login and script don't work. 
Example: 
`# ArubaOS device`
`aruba;script;hrancid -t aruba`
`aruba;login;hlogin`

**Comment by miken32** [comment]
That’s because the 2930 is an HP switch. As the readme says, this script is for old ArubaOS switches; I don’t even know if they’re still making them. I’ve since moved on to Ruckus switches (which are actually Brocade, which used to be Foundry!)

**Comment by jrbinks** [comment]
This is all rather complicated these days but:

The 2930M is a newer Aruba (~ HPE) switch, running "ArubaOS-Switch" -- this being what they now call Provision, the operating system, but it's basically the same.

I think Mike's script script is really for devices running AOS, which is the operating system on the wireless controllers (and as the readme notes models like S1500).

This page clarifies a bit: https://community.arubanetworks.com/community-home/digestviewer/viewthread?MID=16761

_"To complete the overview, the legacy Aruba Mobility Access Switches (MAS: S1500, S2500, S3500, end-of-sale), ran ArubaOS which was derived from the Aruba controllers."_

I think referring to "ArubaOS" in the readme is probably misleading, and "AOS" would be more accurate, since that's what they now seem to call it, and would help distinguish between that, ArubaOS-Switch (I think most just call this "ArubaOS"), and ArubaOSCX, which is what runs on the higher end.  Let's not even get into Comware ...

In theory, the standard rancid HP support for Provision should work for 2930M, in practice it may not have been tuned for newer models.  I should try, I have some 2930Fs.

Mike said he no longer has these models so is unlikely to continue development himself, although he did a merge of a trivial change.  So there needs to be a bit of thought about that.  I have wireless controllers, so Mike's is useful to me anyway.  Maybe I just have to fork and continue ...

**Comment by miken32** [comment]
Oh I hadn't realized they'd taken the ArubaOS name and applied it to the HP line. That seems needlessly confusing. I'll try to put some more clarification into the readme (beyond listing what models I wrote the script for.)

**Comment by pvdmarel** [comment]
I'm not the network expert, so I searched for "aruba rancid" and came up to this github, and the command do make sense for the HP Aruba 2930 series, however to make it work with the 2930M (we don't have other types at the moment) it needs to use hrancid and hlogin. 
@miken32 You did create a module that is with just a minor change in the config is usable for more than you originally intended. 
@jrbinks the original hp support has different commands preset. It does not work out of the box with the 2930M. With this module and just the configuration from the example slightly changed to use hrancid and hlogin it does work wonderfully..

**Comment by jrbinks** [comment]
It would probably be better for in-built rancid support for HP to be modified to support the ArubaOS-Switch models, since they are Procurve-based, and for this to be kept for the AOS ones as that is what it is directed at.  Certainly some of the commands that are in mike's should be compared with the ones for standard HP rancid and added to the latter if they are useful.

(Unfortunately @haussli isn't very responsive to suggested changes to canonical rancid, at least at the moment.  I have long-outstanding push requests and other things that I wanted to follow-up with).

**Comment by jrbinks** [comment]
> That seems needlessly confusing. I'll try to put some more clarification into the readme (beyond listing what models I wrote the script for.)

"needlessly confusing" describes the 3Com/H3C/HP/HPE/Aruba operating system mess all over, I'm afraid.

For added fun, some earlier "procurve" stuff had same heritage as earlier Foundry (Brocade) ...

**Comment by miken32** [comment]
I haven't regularly used HPE switches in 3-4 years, but it was well after the Aruba rebranding. Mostly I worked with 2530 and 2920 switches. The underlying OS didn't change from ProVision so I'd be surprised if the commands from this old module all worked without issue.

Agree that tweaking the existing code to support current switches is the way to go; I expect there's little call for support of the mobility access switches and controllers these days. Really though the whole Rancid codebase needs a ground-up rewrite. To call this software dated would be an understatement of epic proportions; architecturally, it's almost unchanged since it was written > 20 years ago. I too would be unenthusiastic about maintaining it!

BTW the _current_ switches are identified as running "AOS-S" as in [these release notes](https://www.arubanetworks.com/techdocs/AOS-Switch/RN/16.10/AOS-S%20Switch%2016.10.0021%20Release%20Notes.pdf) for example.

**Comment by jrbinks** [comment]
> Agree that tweaking the existing code to support current switches is the way to go; I expect there's little call for support of the mobility access switches and controllers these days. Really though the whole Rancid codebase needs a ground-up rewrite. To call this software dated would be an understatement of epic proportions; architecturally, it's almost unchanged since it was written > 20 years ago. I too would be unenthusiastic about maintaining it!

Can't disagree with that, although it has slowly changed to add in useful abstractions.  But there are still too many subtly different per-vendor login scripts with lots of duplication.  plogin (polylogin) was developed, but I haven't looked to see how flexible it is and how much it could do away with that duplication!  At least large amounts of apparent duplication are now imported from a single source file these days rather than literal duplication across many, leading to inconsistencies.  But, it is what it is and I still stick with it!

Regardless of that, your script is useful for the wireless controllers still as a current product, and that's the context in which I would use it.

> BTW the _current_ switches are identified as running "AOS-S" as in [these release notes]

More inconsistency!  Note the URL says "AOS-Switch" :)  Even in one of the tables in those notes: "Refer to the Aruba 2920 Management and Configuration Guide for AOS-S Switch 16.10 and Aruba MIB and Trap Support Matrix for AOS-S Switch 16.10 for more information.".  So AOS-S, AOS-S Switch, AOS-Switch?

On the wireless stuff, from this page and the data sheet linked from it: https://www.arubanetworks.com/products/network-management-operations/arubaos/ I think the claim would be that formally the wireless switch software is plain ArubaOS (and also referred to as AOS), the provision-like software is ArubaOS-Switch (AOS-S) [and by implication the higher-end Linux-based OS is ArubaOS-CX (AOS-CX)].  Clear as mud!

So "AOS" and "ArubaOS" seem to describe your module, "AOS-S" and "ArubaOS-Switch" describes what we used to call Procurve and /should/ be fully supported by the h* modules in rancid, subject to required updates.

So @pvdmarel really should be using the native rancid HP procurve support, and that should be tweaked where there are issues.

I've not done rancid dev for a while, I need to catch up on the current repo and see if there is anything I can do to help @pvdmarel (but he seems happy enough with getting yours working - I'm not sure encouraging it to work  by altering the documentation as he suggests for 2930x is a good idea as it is ultimately misleading).

**Comment by jrbinks** [comment]
In case anyone falls into this and it utterly befuddled, when I wrote some support for ArubaOS-CX, I tried to make clear exactly what it was for and what it wasn't for: https://github.com/jrbinks/rancid-arubaoscx
